import { TemplateType } from "@prisma/client";

// IMPORTANT: These templates are AI-DRAFTED and gated by reviewedByLegal=false.
// The escalation engine refuses to dispatch any notice whose template has
// reviewedByLegal=false. Templates only become live after a human legal reviewer
// (IFF / SFLC.in) updates the row in production. See FORBIDDEN list in
// Desktop/Asmita/TODOS.md rule 2.
//
// Drafting constraints honored below:
// - No "phone", "mobile", or "aadhaar" anywhere in body text (renderer rejects).
// - Variables limited to the set already supplied by notice-router callers:
//   caseReference, platformName, url, declarationReference.
// - Specific subsection citations of the IT Rules (Amendment) 2026 are
//   intentionally HEDGED ("as amended in 2026") because the AI researcher only
//   has secondary-source coverage of the amendment, not the gazette text.
//   The legal reviewer must replace these hedges with verified rule numbers.
// - DMCA template carries the 17 U.S.C. § 512(c)(3) skeleton so the legal
//   reviewer is editing a procedurally-shaped draft, not writing from scratch.

export const templateSeeds = [
  {
    templateType: TemplateType.IT_RULES_2021,
    subjectTemplate:
      "Urgent NCII takedown request under IT Rules 2021 / 2026 - {{caseReference}}",
    bodyTemplate: [
      "To: The Resident Grievance Officer, {{platformName}}",
      "",
      "Subject: Statutory NCII takedown notice under IT Rules 2021 (as amended) for {{caseReference}}",
      "",
      "Madam / Sir,",
      "",
      "1. INTRODUCTION",
      "Asmita is a public-interest platform that assists adult residents of India in submitting takedown notices for non-consensual intimate imagery (NCII) under the Information Technology Act, 2000 and rules made thereunder. This notice is being filed on behalf of a complainant who has executed a signed digital declaration confirming the matters set out below.",
      "",
      "2. COMPLAINANT IDENTIFICATION",
      "The complainant is a verified adult Indian resident. Identifying information has been retained by Asmita under encryption and is not reproduced in this notice in order to limit further exposure. Identifying details will be furnished directly to your office on a verified request consistent with applicable data-minimisation obligations.",
      "Declaration reference: {{declarationReference}}",
      "",
      "3. URL TO BE ACTED UPON",
      "Asmita case reference: {{caseReference}}",
      "URL hosted on your service: {{url}}",
      "Asmita has at no point retrieved, viewed, downloaded, stored, or displayed the content at the above URL. The URL is being supplied solely as a locator for your moderation team.",
      "",
      "4. NATURE OF THE COMPLAINT",
      "The complainant has stated, under her signed declaration, that the content at the above URL: (a) depicts or purports to depict her; (b) is intimate in nature within the meaning of applicable Indian law; and (c) has been published, hosted, or transmitted on your service without her consent. The complainant is the person depicted, or her authorised representative, within the meaning of the applicable rules.",
      "",
      "5. STATUTORY BASIS",
      "This notice is filed under and seeks action consistent with the following provisions, which are listed without prejudice to any further provisions that may apply:",
      "(a) Section 67 and Section 67A of the Information Technology Act, 2000;",
      "(b) Section 66E of the Information Technology Act, 2000 (violation of privacy);",
      "(c) Section 79 of the Information Technology Act, 2000 read with the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, including the obligations of significant social media intermediaries under Rule 3 and Rule 4 as applicable;",
      "(d) the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, as amended in 2026 prescribing accelerated removal timelines for NCII and synthetically-generated intimate content; and",
      "(e) the Bharatiya Nyaya Sanhita, 2023 sections corresponding to voyeurism and publication of obscene material.",
      "",
      "6. REQUESTED ACTION",
      "The complainant respectfully requests that {{platformName}}:",
      "(i) acknowledge receipt of this notice within 24 hours of receipt;",
      "(ii) disable access to the URL identified at paragraph 3 above on an accelerated basis consistent with the applicable rules and any sectoral standard operating procedure issued by the Ministry of Electronics and Information Technology;",
      "(iii) preserve the underlying account records and content for a reasonable period for the purpose of any subsequent investigation by Indian law-enforcement agencies; and",
      "(iv) confirm action taken to the address in paragraph 7 below.",
      "",
      "7. RETURN ADDRESS FOR ACKNOWLEDGEMENT",
      "All communications concerning this notice should be addressed to Asmita at the address from which this notice is sent, quoting the case reference {{caseReference}}.",
      "",
      "8. DECLARATION",
      "The complainant has executed a digital declaration affirming the matters set out above and confirming that the complaint is made in good faith and to the best of her knowledge and belief. The declaration has been retained by Asmita and is available for inspection by your designated Grievance Officer on a verified written request.",
      "",
      "Filed by Asmita on behalf of the complainant.",
      "Case reference: {{caseReference}}",
      "",
      "[DRAFT - PENDING LEGAL REVIEW BY IFF / SFLC.in - DO NOT DISPATCH]",
    ].join("\n"),
    legalCitations: [
      "IT Act 2000 s.66E",
      "IT Act 2000 s.67",
      "IT Act 2000 s.67A",
      "IT Act 2000 s.79",
      "IT (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021",
      "IT (Intermediary Guidelines and Digital Media Ethics Code) Amendment Rules, 2026",
      "BNS 2023 (voyeurism / obscenity provisions)",
    ],
  },
  {
    templateType: TemplateType.DMCA,
    subjectTemplate:
      "Non-consensual intimate imagery removal request (priority) - {{caseReference}}",
    bodyTemplate: [
      "To: The Designated Agent / Trust and Safety Team, {{platformName}}",
      "",
      "Subject: Notification under 17 U.S.C. § 512(c)(3) and 15 U.S.C. § 6851 (TAKE IT DOWN Act) - {{caseReference}}",
      "",
      "Madam / Sir,",
      "",
      "1. NATURE OF THIS NOTICE",
      "This communication is provided as both: (a) a takedown notification under the Digital Millennium Copyright Act, 17 U.S.C. § 512(c)(3), to the extent the complainant retains rights in the work; and (b) a notification of non-consensual intimate visual depiction under the Tools to Address Known Exploitation by Immobilizing Technological Deepfakes on Websites and Networks Act of 2025 (TAKE IT DOWN Act), 15 U.S.C. § 6851, which obligates covered platforms to remove identified non-consensual intimate visual depictions within 48 hours of a valid notification.",
      "",
      "2. IDENTIFICATION OF THE WORK / DEPICTION",
      "The complainant is the identifiable person depicted in the visual material located at the URL identified in paragraph 3 below. The depiction is intimate in nature and was published, transmitted, or otherwise made available on your service without the complainant's consent.",
      "",
      "3. IDENTIFICATION OF MATERIAL TO BE REMOVED",
      "Asmita case reference: {{caseReference}}",
      "URL on your service: {{url}}",
      "Asmita has not retrieved, viewed, downloaded, stored, or displayed the content at the above URL at any point. The URL is supplied solely as a locator.",
      "",
      "4. CONTACT INFORMATION",
      "All correspondence concerning this notice should be addressed to Asmita at the address from which this notice has been sent, quoting case reference {{caseReference}}. The complainant's personal contact details have been intentionally omitted from this notice for the complainant's safety; they will be furnished on a verified written request from your designated agent.",
      "Declaration reference: {{declarationReference}}",
      "",
      "5. GOOD-FAITH STATEMENT",
      "The complainant has, by way of a signed digital declaration retained by Asmita, stated her good-faith belief that: (a) the material identified at paragraph 3 above is a non-consensual intimate visual depiction of her within the meaning of 15 U.S.C. § 6851; and (b) to the extent any portion of the material is subject to copyright in which she retains rights, its publication on your service is not authorised by the rights-holder, the rights-holder's agent, or the law.",
      "",
      "6. STATEMENT OF ACCURACY AND AUTHORITY",
      "The information contained in this notification is accurate to the best of the complainant's knowledge and belief. The complainant has affirmed, under penalty of the laws applicable to her, that she is the identifiable person depicted, or is the authorised representative of that person.",
      "",
      "7. REQUESTED ACTION",
      "The complainant respectfully requests that {{platformName}}:",
      "(i) remove or disable access to the URL identified at paragraph 3 above as soon as possible and in any event within the timelines prescribed by 15 U.S.C. § 6851(b) (48 hours from receipt of valid notification);",
      "(ii) preserve the underlying account records and content for a reasonable period in order to assist any subsequent investigation by competent authorities; and",
      "(iii) confirm action taken to the return address identified in paragraph 4.",
      "",
      "8. SIGNATURE",
      "Filed electronically by Asmita on behalf of the complainant. The complainant's signed digital declaration is retained by Asmita and is available to your designated agent on verified written request.",
      "",
      "Case reference: {{caseReference}}",
      "",
      "[DRAFT - PENDING LEGAL REVIEW BY IFF / SFLC.in - DO NOT DISPATCH]",
    ].join("\n"),
    legalCitations: [
      "17 U.S.C. § 512(c)(3) (DMCA)",
      "15 U.S.C. § 6851 (TAKE IT DOWN Act, 2025)",
    ],
  },
  {
    templateType: TemplateType.IT_RULES_AND_DMCA,
    subjectTemplate:
      "Joint Indian and international NCII takedown notice - {{caseReference}}",
    bodyTemplate: [
      "To: The Resident Grievance Officer (India) and the Designated Agent / Trust and Safety Team, {{platformName}}",
      "",
      "Subject: Joint statutory notice for the removal of non-consensual intimate imagery - {{caseReference}}",
      "",
      "Madam / Sir,",
      "",
      "1. PURPOSE",
      "This communication is filed as a single joint notice under both Indian and international legal frameworks because the platform identified above operates Grievance Officer obligations in India as well as a designated agent for takedown notifications outside India. The intent is to enable your respective teams to act on whichever basis is procedurally cleanest, without the complainant having to file two parallel notices.",
      "",
      "2. COMPLAINANT",
      "The complainant is a verified adult Indian resident. Identifying information has been retained by Asmita under encryption and is not reproduced in this notice in order to limit further exposure. Declaration reference: {{declarationReference}}.",
      "",
      "3. MATERIAL",
      "Asmita case reference: {{caseReference}}",
      "URL on your service: {{url}}",
      "Asmita has not retrieved, viewed, downloaded, stored, or displayed the content at the above URL.",
      "",
      "4. STATUTORY BASES ASSERTED",
      "Indian law: Section 66E, Section 67, Section 67A, and Section 79 of the Information Technology Act, 2000; the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, as amended in 2026 prescribing accelerated NCII timelines; and the relevant provisions of the Bharatiya Nyaya Sanhita, 2023.",
      "United States law (if applicable to the operator): 17 U.S.C. § 512(c)(3) and 15 U.S.C. § 6851 (TAKE IT DOWN Act, 2025).",
      "",
      "5. CONFIRMATIONS AND GOOD-FAITH STATEMENT",
      "The complainant has, by way of a signed digital declaration retained by Asmita, confirmed that: (a) the material at the URL above depicts her; (b) it is intimate in nature; (c) its publication on your service is without her consent; and (d) this notice is filed in good faith. The information in this notice is accurate to the best of her knowledge and belief.",
      "",
      "6. REQUESTED ACTION",
      "The complainant respectfully requests that {{platformName}}:",
      "(i) acknowledge receipt within 24 hours;",
      "(ii) remove or disable access to the URL identified at paragraph 3 above on an accelerated basis consistent with the shortest applicable statutory window;",
      "(iii) preserve account and content records for a reasonable period for any subsequent investigation by competent authorities; and",
      "(iv) confirm action taken to Asmita at the return address from which this notice is sent, quoting case reference {{caseReference}}.",
      "",
      "Filed electronically by Asmita on behalf of the complainant.",
      "Case reference: {{caseReference}}",
      "",
      "[DRAFT - PENDING LEGAL REVIEW BY IFF / SFLC.in - DO NOT DISPATCH]",
    ].join("\n"),
    legalCitations: [
      "IT Act 2000 s.66E",
      "IT Act 2000 s.67",
      "IT Act 2000 s.67A",
      "IT Act 2000 s.79",
      "IT (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021",
      "IT (Intermediary Guidelines and Digital Media Ethics Code) Amendment Rules, 2026",
      "17 U.S.C. § 512(c)(3) (DMCA)",
      "15 U.S.C. § 6851 (TAKE IT DOWN Act, 2025)",
      "BNS 2023 (voyeurism / obscenity provisions)",
    ],
  },
  {
    templateType: TemplateType.HASH_ADVISORY,
    subjectTemplate:
      "NCII proactive blocking request (perceptual hash advisory) - {{caseReference}}",
    bodyTemplate: [
      "To: The Resident Grievance Officer / Trust and Safety Team, {{platformName}}",
      "",
      "Subject: Advisory and proactive blocking request for non-consensual intimate imagery, with perceptual hash annex - {{caseReference}}",
      "",
      "Madam / Sir,",
      "",
      "1. PURPOSE",
      "Asmita is a public-interest platform that assists adult residents of India affected by non-consensual intimate imagery (NCII). This communication is an advisory and proactive blocking request: the complainant reports that intimate content depicting her has been shared, or is threatened to be shared, without her consent, including on or via your service. To enable your moderation systems to detect and block this content without any further dissemination of the material itself, this notice encloses perceptual hashes of the content in the annex below.",
      "",
      "2. COMPLAINANT",
      "The complainant is a verified adult Indian resident who has executed a signed digital declaration retained by Asmita under encryption. Identifying information is not reproduced in this notice in order to limit further exposure and will be furnished to your office on a verified written request consistent with applicable data-minimisation obligations.",
      "Declaration reference: {{declarationReference}}",
      "Asmita case reference: {{caseReference}}",
      "",
      "3. NATURE OF THE PERCEPTUAL HASHES",
      "The hashes in the annex were generated on the complainant's own device using the open-source PDQ perceptual hashing algorithm published by Meta through the ThreatExchange project. Asmita has at no point received, retrieved, viewed, stored, or transmitted the underlying media. A perceptual hash is a one-way digital fingerprint: it permits your systems to identify visually matching media but cannot be reversed to reconstruct the image.",
      "",
      "4. STATUTORY BASIS",
      "This request is made under and seeks action consistent with the following provisions, listed without prejudice to any further provisions that may apply:",
      "(a) Section 79 of the Information Technology Act, 2000 read with the due-diligence obligations of intermediaries under Rule 3(1)(b) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021;",
      "(b) Rule 3(2)(b) of the said Rules, prescribing accelerated complaint-based removal of content depicting a person in a private area or sexual act, as amended in 2026 with accelerated NCII timelines;",
      "(c) Sections 66E, 67, and 67A of the Information Technology Act, 2000; and",
      "(d) the relevant provisions of the Bharatiya Nyaya Sanhita, 2023 corresponding to voyeurism and publication of obscene material.",
      "",
      "5. REQUESTED ACTION",
      "The complainant respectfully requests that {{platformName}}:",
      "(i) acknowledge receipt of this advisory within 24 hours of receipt;",
      "(ii) ingest the perceptual hashes in the annex into your proactive detection or hash-matching systems so that matching uploads are blocked at or promptly after upload;",
      "(iii) remove or disable access to any matching content already published on your service on an accelerated basis consistent with the applicable rules;",
      "(iv) preserve account and content records relating to any matches for a reasonable period for the purpose of any subsequent investigation by Indian law-enforcement agencies; and",
      "(v) confirm action taken to Asmita at the address from which this notice is sent, quoting case reference {{caseReference}}.",
      "",
      "6. GOOD FAITH AND ACCOUNTABILITY",
      "The complainant has affirmed by signed digital declaration that she appears in the content represented by the enclosed hashes (or is the authorised reporter), that its sharing is without consent, and that this request is made in good faith. Every hash submission is reviewed by an Asmita administrator before dispatch. Your office may challenge or seek clarification of this request through Asmita, quoting the case reference.",
      "",
      "Filed electronically by Asmita on behalf of the complainant.",
      "Case reference: {{caseReference}}",
      "",
      "[The perceptual hash annex is appended below this notice body.]",
      "",
      "[DRAFT - PENDING LEGAL REVIEW BY IFF / SFLC.in - DO NOT DISPATCH]",
    ].join("\n"),
    legalCitations: [
      "IT Act 2000 s.66E",
      "IT Act 2000 s.67",
      "IT Act 2000 s.67A",
      "IT Act 2000 s.79",
      "IT (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, Rule 3(1)(b) and Rule 3(2)(b)",
      "IT (Intermediary Guidelines and Digital Media Ethics Code) Amendment Rules, 2026",
      "BNS 2023 (voyeurism / obscenity provisions)",
    ],
  },
] as const;
