// Client-side AI provenance reader.
//
// This module runs ONLY in the browser. It reads credentials the file already
// carries (C2PA Content Credentials + IPTC/XMP/EXIF metadata) to see whether an
// AI tool declared that it made or edited the image. It never uploads the file
// and never analyses pixels, so it only ever reports facts the file states about
// itself: it does not guess, and it cannot falsely accuse a genuine photo.

const C2PA_VERSION = "0.30.17";
const C2PA_WASM = `https://cdn.jsdelivr.net/npm/c2pa@${C2PA_VERSION}/dist/assets/wasm/toolkit_bg.wasm`;
const C2PA_WORKER = `https://cdn.jsdelivr.net/npm/c2pa@${C2PA_VERSION}/dist/c2pa.worker.min.js`;

// IPTC DigitalSourceType values that mean "made with generative AI".
const AI_SOURCE_TYPES = [
  "trainedalgorithmicmedia",
  "compositewithtrainedalgorithmicmedia",
  "algorithmicmedia",
];

export type ProvenanceResult = {
  ai: boolean;
  /** Human-facing signals, e.g. "IPTC: Created using generative AI". */
  signals: string[];
  tool?: string;
  signer?: string;
  source?: string;
  /** Raw values kept for the "technical details" disclosure. */
  raw: Record<string, string>;
};

function looksAiSource(value: unknown): boolean {
  if (typeof value !== "string") return false;
  const v = value.toLowerCase();
  return AI_SOURCE_TYPES.some((t) => v.includes(t));
}

async function readMetadata(file: File, result: ProvenanceResult): Promise<void> {
  try {
    const exifr = (await import("exifr")).default;
    const data = await exifr.parse(file, {
      xmp: true,
      iptc: true,
      tiff: true,
    });
    if (!data) return;

    // DigitalSourceType can surface under a few key spellings depending on writer.
    const sourceType =
      data.DigitalSourceType ??
      data["Iptc4xmpExt:DigitalSourceType"] ??
      data.digitalSourceType;
    if (looksAiSource(sourceType)) {
      result.ai = true;
      result.source = String(sourceType);
      result.signals.push("IPTC: Created using generative AI");
      result.raw.digitalSourceType = String(sourceType);
    }

    const software = data.Software ?? data.CreatorTool ?? data.HistorySoftwareAgent;
    if (typeof software === "string") {
      result.raw.software = software;
      if (/firefly|dall-?e|midjourney|stable ?diffusion|imagen|gemini|generative/i.test(software)) {
        result.ai = true;
        result.tool = result.tool ?? software;
        result.signals.push(`Metadata names an AI tool: ${software}`);
      }
    }
  } catch {
    // Metadata is optional; ignore parse failures and fall through to C2PA.
  }
}

async function readContentCredentials(file: File, result: ProvenanceResult): Promise<void> {
  try {
    const { createC2pa } = await import("c2pa");
    const c2pa = await createC2pa({ wasmSrc: C2PA_WASM, workerSrc: C2PA_WORKER });
    const { manifestStore } = await c2pa.read(file);
    const manifest = manifestStore?.activeManifest;
    if (!manifest) return;

    if (manifest.signatureInfo?.issuer) {
      result.signer = manifest.signatureInfo.issuer;
      result.raw.signer = manifest.signatureInfo.issuer;
    }
    if (manifest.claimGenerator) {
      result.raw.claimGenerator = manifest.claimGenerator;
    }

    for (const assertion of manifest.assertions?.data ?? []) {
      const label = assertion.label ?? "";
      const value = assertion.data as Record<string, unknown> | undefined;

      // Modern C2PA: actions carry a digitalSourceType per action.
      if (label.startsWith("c2pa.actions") && value?.actions) {
        for (const action of value.actions as Array<Record<string, unknown>>) {
          if (looksAiSource(action.digitalSourceType)) {
            result.ai = true;
            result.source = String(action.digitalSourceType);
            result.signals.push("Content Credentials: an AI tool is recorded in the edit history");
            const agent = action.softwareAgent;
            if (typeof agent === "string") result.tool = result.tool ?? agent;
          }
        }
      }

      // Some writers put digitalSourceType at the assertion root.
      if (looksAiSource(value?.digitalSourceType)) {
        result.ai = true;
        result.source = String(value?.digitalSourceType);
        result.signals.push("Content Credentials: file declares AI generation");
      }
    }

    // Claim generator often names the AI product outright.
    if (!result.tool && /firefly|dall-?e|midjourney|stable ?diffusion|imagen|gemini/i.test(manifest.claimGenerator ?? "")) {
      result.ai = true;
      result.tool = manifest.claimGenerator ?? undefined;
      result.signals.push(`Content Credentials generated by: ${manifest.claimGenerator}`);
    }
  } catch {
    // A missing or unreadable manifest is the common case; not an error to the user.
  }
}

export async function readImageProvenance(file: File): Promise<ProvenanceResult> {
  const result: ProvenanceResult = { ai: false, signals: [], raw: {} };
  await Promise.all([readMetadata(file, result), readContentCredentials(file, result)]);
  return result;
}
